version: '3.8'
services:
  stats-server:
    build: stats-server
    image: stats-server-img
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
  #      - TZ=Asia/Yekaterinburg

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    #      - TZ=Asia/Yekaterinburg

  ewm-service:
    build: ./ewm-service
    image: ewm-service-img
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
#      - TZ=Asia/Yekaterinburg

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - TZ=Asia/Yekaterinburg

