version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats-server-img
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
        - TZ=Asia/Yekaterinburg

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - TZ=Asia/Yekaterinburg
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U root -d statsdb'" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-service:
    build: ../vasya/java-explore-with-me/ewm-service
    image: ewm-service-img
    container_name: ewm-service-cont
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
